### ISSUE TITLE
Dispatcher type validation is probably a bit too strict (bug)

### ISSUE THREAD

**Issue by hlegendre** [valyala/gorpc#12]
Hi,

I was trying to pass a struct containing a `time.Time` object between the server and the client and I got the following panic just after running:

> gorpc.Dispatcher: response in the function [Foo.Bar] cannot contain struct without exported fields [time.Time] in the field [Start] of struct [foo.Result]

It appears that the dispatcher, in the `validateType ` function, checks for at least one exported field in each struct it sees and therefore reject `time.Time` which has none. This seems overly strict because time.Time implements the `GobEncoder` and `GobDecoder` interfaces even with no exported fields and therefore should be able to pass on the wire without problem.

I am fairly new to Golang and therefore have no idea how this could be fixed but I am under the impression that it is a bug of gorpc and not an intended feature.

Could you have a look, please?

Best,

HLG

**Comment by hlegendre** [comment]
needless to say the net/rpc library works perfectly with `time.Time`

**Comment by valyala** [comment]
Just fixed this in the issue #13.
