### ISSUE TITLE
Dealing with time.Time

### ISSUE THREAD

**Issue by avaman** [valyala/gorpc#13]
What is the best way to deal with time.Time fields in the structures?

**Comment by valyala** [comment]
Just register time.Time with `gorpc.RegisterType(&time.Time{})`. See https://github.com/valyala/gorpc/commit/95e3cf011267071626699d25103a422879394674 for details.

**Comment by valyala** [comment]
I'll fix `cannot contain struct without exported fields` warning tomorrow.

**Comment by valyala** [comment]
Now it should be OK using time.Time in Dispatcher-assisted RPCs.
