### ISSUE TITLE
Is it possible to add support of struct{}?

### ISSUE THREAD

**Issue by ikkeps** [valyala/gorpc#14]
In many cases sets implemented as map[T]struct{}. It would be nice to support it to avoid extra convertion on both server and client sides.

Currently Dispatcher AddFunc panics:

```
... cannot contain struct without exported fields [struct {}] in the value of map...
```

I could implement custom GobDecoder/GobDecoder for map[T]struct{}-type in my code, but it would be nice if gorpc supports it.

**Comment by ikkeps** [comment]
I hacked it like this https://github.com/ikkeps/gorpc/commit/0b4d2f93bb93a4ef4656e1509475bb8b1d0b1d7d 
Not sure about this. All tests passes.

**Comment by valyala** [comment]
@ikeps, thanks for the patch!
