### ISSUE TITLE
windows call timeout

### ISSUE THREAD

**Issue by gyf19** [valyala/gorpc#18]
go version go1.5.1 windows/amd64

go test -run ExampleDispatcher_serviceCalls

--- FAIL: ExampleDispatcher_serviceCalls (120.06s)
got:
Get=<nil>, gorpc.Client: [:7892]. Cannot obtain response during timeout=20s
Get=<nil>, gorpc.Client: [:7892]. Cannot obtain response during timeout=20s
Set=<nil>, gorpc.Client: [:7892]. Cannot obtain response during timeout=20s, 456

GetError42=<nil>, gorpc.Client: [:7892]. Cannot obtain response during timeout=2
0s
GetError42=<nil>, gorpc.Client: [:7892]. Cannot obtain response during timeout=2
0s
DDDD=<nil>, gorpc.Client: [:7892]. Cannot obtain response during timeout=20s
want:
Get=123, <nil>
Get=456, <nil>
Set=<nil>, <nil>, 78
GetError42=78, <nil>
GetError42=<nil>, error42
DDDD=13, <nil>
FAIL
exit status 1

**Comment by valyala** [comment]
@gyf19 , unfortunately I have no windows machines to investigate this issue further.

Just a guess - try modifying the following line in [example_service_test.go](https://github.com/valyala/gorpc/blob/master/example_service_test.go):

```go
        addr := ":7892"
```

to

```to
        addr := "localhost:17892"
```

**Comment by gyf19** [comment]
Praise , solved

**Comment by valyala** [comment]
@gyf19 , it would be great if you post the solution here :)
