### ISSUE TITLE
Dispatcher couples server and client

### ISSUE THREAD

**Issue by dwlnetnl** [valyala/gorpc#7]
It seems that you need to register functions or services with the Dispatcher that are both used by the client and server. Because of this I'm not able to build the server and client code separately. I'd like to see the dispatcher decoupled from the server and client.

I don't have any idea what is a nice way to implement this. Could you give directions, than I can create a pull request with the changes.

**Comment by valyala** [comment]
I have no idea yet on how to properly decouple client code from server code when using Dispatcher. As a workaround, you can register function and service stubs on the client, since Dispatcher verifies only function / service names on client side.

**Comment by valyala** [comment]
I removed dependency on server handler implementations from client code at the cost of required manual registration of non-trivial request and response types on client side. See updated docs for DispatcherClient methods.

It is possible to remove manual registration of non-trivial request and response types on client side. But this requires API and transport protocol modifications.
