### ISSUE TITLE
Cannot decode request

### ISSUE THREAD

**Issue by krzysztofantczak** [valyala/gorpc#8]
Hi,

When running example code from README:
```
2015/08/11 12:31:48 Obtained request foobar from the client 127.0.0.1:62891
2015/08/11 12:31:48 gorpc.Server: [127.0.0.1:62891]->[:12345]. Cannot decode request: [unexpected EOF]
```

**Comment by valyala** [comment]
This is just innocent log message on the server, which meant 'the client has been disconnected'. I patched the server, so such misleading messages are suppressed now.
